name: Generate Repo Tree

on:
  schedule:
    - cron: "0 8,22 * * *"
  workflow_dispatch:

jobs:
  generate_tree_and_move:
    runs-on: ubuntu-latest
    steps:
    - name: checkout external repository (docs)
      uses: actions/checkout@v2
      with:
        repository: NaN1fy/docs
        path: './esterno'
    - name: checkout internal repository (this)
      uses: actions/checkout@v2
      with:
        path: './interno'
        token: ${{secrets.NAN1FY_SITE}}
    - name: generate tree
      run: |  
        cd ./esterno
        tree -Js > repo_tree.json
    - name: mv tree & add date
      run: |
        mv esterno/repo_tree.json interno/assets/data/repo_tree.json
        mv esterno/documents/RTB/interni/glossario*.tex interno/assets/data/glossario*.tex
        touch interno/assets/data/lmod.txt
        stat -c "%y" interno/assets/data/repo_tree.json > interno/assets/lmod.txt
    - name: run Python script
      run: |
        cd interno
        python3 assets/script/glossario.py
    - name: commit to internal repository (site)
      run: |
        cd interno
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add assets/data/repo_tree.json 
        git add assets/data/lmod.txt
        git add assets/script/glossario.py
        git commit --allow-empty -m "Automatic update $(date +%Y-%m-%d)"
        git push
